import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderPart1 from "@/components/1header/HeaderPart1";
import Headerpart2 from "@/components/1header/Headerpart2";
import HeaderPart3 from "@/components/1header/HeaderPart3";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"  />
        <link
          href="https://fonts.googleapis.com/css2?family=Pixelify+Sans&display=swap"
          rel="stylesheet"
        />
        {/* <title>Aniket Panchal Portfolio</title>
        <link rel="icon" href="/mincraft2.png" type="image/svg+xml" /> */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderPart1 />
        <HeaderPart3 />
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  );
}
