import type { Metadata } from "next";
import { Geist, Geist_Mono, Pixelify_Sans  } from "next/font/google";
import "./globals.css";
import HeaderPart1 from "@/components/1header/HeaderPart1";
// import Headerpart2 from "@/components/1header/Headerpart2";
import HeaderPart3 from "@/components/1header/HeaderPart3";

const pixelify = Pixelify_Sans({
  weight: ["400"], // or multiple weights like ['400', '700']
  subsets: ["latin"],
  variable: "--font-pixelify-sans", // optional CSS variable
  display: "swap", // recommended
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pixelify.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <HeaderPart1 />
        <HeaderPart3 /> */}
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  );
}
